name: called_workflows

#
# Documentation:
# https://github.com/github/super-linter
#

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: 'yuya-hanzawa/base_repo'
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Output File Content
        working-directory: 'sample'
        run: |
          pwd && ls && cat read_files
